version: "2"

services:
  tengine:
    image: tengine:latest
    container_name: tengine
    hostname: tengine
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - $PWD/conf:/usr/local/nginx/conf/vhost
     - /Users/txm/develop/wms:/Users/txm/develop/wms
     - /Users/txm/develop/cbt-web:/Users/txm/develop/cbt-web
    environment:
      - TZ=Asia/Shanghai # 设置时区
