version: "2"

services:

    mongo:
        image: mongo:4.4
        container_name: mongo
        command: mongod --auth --wiredTigerCacheSizeGB 3.2
        restart: always
        mem_limit: 4g
        ports:
            - "37017:27017/tcp"
        volumes:
            - $PWD/mongo/data/db:/data/db
        environment:
            TZ: Asia/Shanghai # 设置时区
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ttx2011
        networks:
            - base-net
    redis:
        image: redis:5.0
        container_name: redis
        hostname: redis
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf
        #command: redis-server --appendonly yes
        ports:
            - 36379:6379
        volumes:
            - $PWD/redis/data:/data
            - $PWD/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - TZ=Asia/Shanghai # 设置时区
        networks:
            - base-net
    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        hostname: rabbit
        restart: always
        environment:
            - TZ=Asia/Shanghai # 设置时区
            - RABBITMQ_DEFAULT_USER=ttx
            - RABBITMQ_DEFAULT_PASS=ttx2011
        ports:
            - "35672:5672"
            - "35673:15672"
        volumes:
            - $PWD/rabbitmq/data/rabbitmq:/var/lib/rabbitmq
        networks:
            - base-net
    mysql:
        image: mysql:5.7.44
        container_name: mysql
        hostname: mysql
        ports:
            - 30001:3306
        volumes:
            - ./mysql/conf/mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/container_data/mysql:/var/lib/mysql
            - ./mysql/sqldumps:/sqldumps
        environment:
            - MYSQL_ROOT_PASSWORD=ttx2011
            - TZ=Asia/Shanghai # 设置时区
        networks:
            - base-net
    scheduler:
        image: registry.cn-hangzhou.aliyuncs.com/loghub/cbt-scheduler:2.9.7
        container_name: scheduler
        logging:
            options:
                max-file: "3"
                max-size: "20m"
        environment:
            - TZ=Asia/Shanghai
            - NACOS_DISCOVERY_ENABLED=false
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_USERNAME=ttx
            - MONGO_PASSWORD=ttx2011
            - MONGO_DB_LIST=["loreal-wms-prod"]
        ports:
            - "9214:9221"
        networks:
            - base-net
    wms:
        image: tangxm1314/wms
        container_name: wms
        ports:
            - "6001:9210/tcp"
        volumes:
            - ./wms/application-k8s.yml:/app/resources/application-k8s.yml
        environment:
            TZ: "Asia/Shanghai"
            LICENSE_SERVER: http://10.72.64.229:30008
            CBT_HOME_PAGE: "/index.html?customer=loreal-wms-prod&lang=zh"
            # mysql
            MYSQL_URL: "jdbc:mysql://mysql/loreal-wms-prod?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false"
            MYSQL_USERNAME: "root"
            MYSQL_PASSWORD: "ttx2011"
            # redis
            REDIS_HOST: "redis"
            REDIS_DATABASE: "0"
            REDIS_PORT: "6379"
            REDIS_PASSWORD: "ttx2011"
            AUTHREDIS_HOST: "redis"
            AUTHREDIS_DATABASE: "0"
            ### rabbit
            RABBIT_HOST: "rabbitmq"
            RABBIT_PORT: "5672"
            RABBIT_USERNAME: "ttx"
            RABBIT_PASSWORD: "ttx2011"
            RABBIT_VIRTUAL_HOST: "/wms1"
            # mongo
            MONGO_HOST: "mongo"
            MONGO_PORT: "27017"
            MONGO_DB: "loreal-wms-prod"
            MONGO_USERNAME: "ttx"
            MONGO_PASSWORD: "ttx2011"
        networks:
            - base-net
networks:
    base-net:
        driver: bridge
        ipam:
            config:
                -   subnet: 192.168.101.0/24
                    gateway: 192.168.101.1
