name: dragonwell_base

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'jdk_base/Dockerfile'
      - 'jdk_base/source.sh'
  schedule:
    - cron: '00 4 * * *'


env:
  ALIYUN_REGISTRY: "${{ vars.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ vars.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Before freeing up disk space
        run: |
          echo "Before freeing up disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      # 增加可用磁盘空间
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 128
          remove-dotnet: 'true'
          remove-haskell: 'true'
          # 如果空间还是不够用，可以把以下开启，清理出更多空间
          # remove-android: 'true'
          # remove-codeql: 'true'
          build-mount-path: '/var/lib/docker/'

      - name: Restart docker
        run: sudo service docker restart

      - name: Free up disk space complete
        run: |
          echo "Free up disk space complete"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all # 支持所有平台，包括 arm64

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # - name: Build and push dragonwell_base amd64 base
      #   run: |
      #     echo "Building for AMD64..."
      #     # 设置 DOCKER_DEFAULT_PLATFORM 以确保默认使用 amd64
      #     export DOCKER_DEFAULT_PLATFORM=linux/amd64
      #     # 打包镜像并上传
      #     echo "docker build dragonwell_base amd64 base"
      #     docker build -t $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/dragonwell:base_amd64_latest -f jdk_base/Dockerfile .
      #     docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/dragonwell:base_amd64_latest
      #
      # - name: Build and push dragonwell_base arm64 base
      #   run: |
      #     echo "Building for ARM64..."
      #     # 设置 DOCKER_DEFAULT_PLATFORM 以确保默认使用 arm64
      #     export DOCKER_DEFAULT_PLATFORM=linux/arm64
      #     # 打包镜像并上传
      #     echo "docker build dragonwell_base arm64 base"
      #     docker build -t $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/dragonwell:base_arm64_latest -f jdk_base/Dockerfile .
      #     docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/dragonwell:base_arm64_latest
      - name: Build and push dragonwell_base
        uses: docker/build-push-action@v6
        with:
          file: jdk_base/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.ALIYUN_REGISTRY }}/${{ vars.ALIYUN_NAME_SPACE }}/dragonwell:base_latest